// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export interface SiteSettings {
    name: string;
    locale: string;
    recaptcha: {
        enabled: boolean;
        siteKey: string;
    };
}
