// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ExtensionFieldValues } from "../../../extensions/formFields.js";
export interface EggFormValues {
    name: string;
    description: string;
    dockerImages: string;
    startup: string;
    featuresText: string;
    forceOutgoingIp: boolean;
    configFrom: number;
    configStop: string;
    configStartup: string;
    configLogs: string;
    configFiles: string;
    extensions: ExtensionFieldValues<'admin.egg'>;
}
