// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export declare const ExtensionContext: import("react").Context<{
    extensionId: string;
    context: string;
} | null>;
export declare function useExtensionCallback<TArgs extends readonly unknown[]>(event: string, callback: (...args: TArgs) => void | Promise<void>): (...args: TArgs) => void;
