// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export declare const EXTENSION_FORM_NAMES: readonly ["admin.user", "admin.node", "admin.server", "admin.egg", "admin.location", "admin.mount", "admin.databaseHost"];
export type ExtensionFormName = (typeof EXTENSION_FORM_NAMES)[number];
export interface ExtensionFormFieldMap {
}
export type ExtensionFieldValues<TForm extends ExtensionFormName> = TForm extends keyof ExtensionFormFieldMap ? Partial<ExtensionFormFieldMap[TForm]> : Record<never, never>;
export type ExtensionFieldValue = string | number | boolean | Array<string | number> | null;
export type LoadedExtensionFieldValues = Record<string, Record<string, ExtensionFieldValue>>;
