// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { AdminNodeResource, AdminServerResource, AdminEggResource, AdminUserResource } from "../api/extensionTypes.js";
export type ExtensionResourceContext = {
    kind: 'admin.node';
    resource: AdminNodeResource;
} | {
    kind: 'admin.server';
    resource: AdminServerResource;
} | {
    kind: 'admin.egg';
    resource: AdminEggResource;
} | {
    kind: 'admin.user';
    resource: AdminUserResource;
};
export declare const ExtensionResourceProvider: import("react").Context<ExtensionResourceContext | null>;
export declare function useCurrentResource(): ExtensionResourceContext | null;
