// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { NodeValues } from "../../../api/admin/nodes/types.js";
import type { NumberInputValue } from "../numberInput.js";
export interface NodeFormValues extends Omit<NodeValues, 'memory' | 'memoryOverallocate' | 'disk' | 'diskOverallocate' | 'uploadSize' | 'daemonListen' | 'daemonSftp'> {
    memory: NumberInputValue;
    memoryOverallocate: NumberInputValue;
    disk: NumberInputValue;
    diskOverallocate: NumberInputValue;
    uploadSize: NumberInputValue;
    daemonListen: NumberInputValue;
    daemonSftp: NumberInputValue;
}
export interface NodeSettingsValues extends NodeFormValues {
    resetSecret: boolean;
}
