// Generated by scripts/generate-sdk-types.mjs. Do not edit.
/** `null` while the input is empty. */
export type NumberInputValue = number | null;
export declare const requiredNumber: (message: string, check?: (value: number) => string | undefined) => ({ value }: {
    value: NumberInputValue;
}) => string | undefined;
export declare const submittedNumber: (value: NumberInputValue) => number;
