// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
export type AlertType = 'success' | 'info' | 'warning' | 'danger';
interface AlertProps {
    type: AlertType;
    title?: React.ReactNode;
    className?: string;
    children: React.ReactNode;
}
export default function Alert({ type, title, className, children }: AlertProps): React.JSX.Element;
export {};
