import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
    input: 'storage/app/private/scribe/openapi.yaml',
    output: {
        path: 'resources/scripts/api/generated',
        clean: true,
        header: [
            '// Generated by @hey-api/openapi-ts.',
            '// Do not edit this directory by hand; run npm run api:generate instead.',
        ],
    },
    plugins: [
        '@hey-api/typescript',
        {
            name: '@hey-api/client-axios',
            baseUrl: false,
            runtimeConfigPath: './resources/scripts/api/hey-api-runtime',
            throwOnError: true,
        },
        {
            name: '@hey-api/sdk',
            client: '@hey-api/client-axios',
            paramsStructure: 'grouped',
        },
        {
            name: '@tanstack/react-query',
            queryKeys: true,
            queryOptions: true,
            mutationKeys: true,
            mutationOptions: true,
        },
    ],
});
