// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import { Checkbox as BaseCheckbox } from '@base-ui/react/checkbox';
export type CheckboxProps = Omit<React.ComponentProps<typeof BaseCheckbox.Root>, 'checked' | 'defaultChecked' | 'onCheckedChange' | 'className' | 'render' | 'children'> & {
    checked: boolean;
    onChange: (checked: boolean) => void;
    className?: string;
};
export default function Checkbox({ checked, onChange, indeterminate, className, ...props }: CheckboxProps): React.JSX.Element;
