// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type * as React from 'react';
declare function Empty({ className, ...props }: React.ComponentProps<'div'>): React.JSX.Element;
declare function EmptyHeader({ className, ...props }: React.ComponentProps<'div'>): React.JSX.Element;
/** `icon` frames a single icon in a tile; `default` leaves the media unframed. */
declare function EmptyMedia({ className, variant, ...props }: React.ComponentProps<'div'> & {
    variant?: 'default' | 'icon';
}): React.JSX.Element;
declare function EmptyTitle({ className, ...props }: React.ComponentProps<'div'>): React.JSX.Element;
declare function EmptyDescription({ className, ...props }: React.ComponentProps<'div'>): React.JSX.Element;
declare function EmptyContent({ className, ...props }: React.ComponentProps<'div'>): React.JSX.Element;
export { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription, EmptyContent };
