// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
export type SelectValue = string | number;
export type SelectOption = {
    value: SelectValue;
    label: React.ReactNode;
    textLabel?: string;
    disabled?: boolean;
};
export interface SelectGroup {
    id?: SelectValue;
    label: string;
    options: SelectOption[];
}
interface BaseSelectProps {
    id?: string;
    options?: SelectOption[];
    groups?: SelectGroup[];
    disabled?: boolean;
    placeholder?: string;
    searchPlaceholder?: string;
    emptyMessage?: string;
    hasError?: boolean;
    'aria-describedby'?: string;
    'aria-invalid'?: boolean;
    onBlur?: React.FocusEventHandler<HTMLInputElement>;
    /** Hands the typed query to the caller and turns off client-side filtering. */
    onSearchChange?: (value: string) => void;
}
interface SingleSelectProps extends BaseSelectProps {
    multiple?: false;
    value: SelectValue | null | undefined;
    onChange: (value: SelectValue) => void;
}
interface MultiSelectProps extends BaseSelectProps {
    multiple: true;
    value: SelectValue[];
    onChange: (value: SelectValue[]) => void;
}
export type SelectProps = SingleSelectProps | MultiSelectProps;
export default function Select(props: SelectProps): React.JSX.Element;
export {};
