// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import { Switch as BaseSwitch } from '@base-ui/react/switch';
export interface SwitchProps {
    checked: boolean;
    onChange: (checked: boolean) => void;
    disabled?: boolean;
    id?: string;
    name?: string;
    label?: string;
    description?: string;
    controlPosition?: 'start' | 'end';
    className?: string;
    onBlur?: React.ComponentProps<typeof BaseSwitch.Root>['onBlur'];
    'aria-label'?: string;
    'aria-labelledby'?: string;
}
export default function Switch({ checked, onChange, disabled, id, name, label, description, controlPosition, className, onBlur, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledBy, }: SwitchProps): React.JSX.Element;
