// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ExtensionFieldValues } from "../../../extensions/formFields.js";
export interface NodeValues {
    name: string;
    description: string;
    locationId: number;
    public: boolean;
    fqdn: string;
    scheme: string;
    behindProxy: boolean;
    maintenanceMode: boolean;
    memory: number;
    memoryOverallocate: number;
    disk: number;
    diskOverallocate: number;
    uploadSize: number;
    daemonListen: number;
    daemonSftp: number;
    daemonBase: string;
    extensions: ExtensionFieldValues<'admin.node'>;
}
