// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export interface UserData {
    uuid: string;
    username: string;
    email: string;
    language: string;
    rootAdmin: boolean;
    useTotp: boolean;
    createdAt: Date;
    updatedAt: Date;
    id?: number;
    firstName?: string;
    lastName?: string;
    externalId?: string | null;
}
