// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ExtensionFormValues } from "../../../extensions/forms.js";
export interface UserValues {
    email: string;
    username: string;
    nameFirst: string;
    nameLast: string;
    password: string;
    rootAdmin: boolean;
    language: string;
    extensions: ExtensionFormValues;
}
