// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export interface UserValues {
    email: string;
    username: string;
    nameFirst: string;
    nameLast: string;
    password: string;
    rootAdmin: boolean;
    language: string;
}
