<?php
return array(
	"confirmpassword" => "Confirm Password",
	"emailsent" => "Your password reset email is on its way.",
	"errorencountered" => "There was an error encountered while attempting to process this request.",
	"failed" => "These credentials do not match our records.",
	"remeberme" => "Remember Me",
	"resetpassword" => "Reset Password",
	"sendlink" => "Send Password Reset Link",
	"throttle" => "Too many login attempts. Please try again in :seconds seconds.",
	"totp_failed" => "The TOTP token provided was invalid. Please ensure that the token generated by your device was valid.",
);