<?php

return [
    'not_authorized' => 'You are not authorized to perform this action.',
    'auth_error' => 'There was an error while attempting to login.',
    'authentication_required' => 'Authentication is required to continue.',
    'remember_me' => 'Remember Me',
    'sign_in' => 'Sign In',
    'forgot_password' => 'Forgot Password?',
    'go_to_login' => 'Go to Login',
    'reset_help_text' => 'Enter your account email address to recive instructions on resetting your password.',
    'recover_account' => 'Recover Account',

    'two_factor' => [
        'label' => '2-Factor Token',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
    ],

    'reset_password_text' => 'Reset your account password.',
    'reset_password' => 'Reset Account Password',
    'email_sent' => 'An email has been sent to you with further instructions for resetting your password.',
    'failed' => 'The credentials provided do not match those we have on record, or the 2FA token provided was invalid.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Passwords must contain at least one uppercase, lowercase, and numeric character and must be at least 8 characters in length.',
    'request_reset' => 'Locate Account',
    '2fa_required' => '2-Factor Authentication',
    '2fa_failed' => 'The 2FA token provided was invalid.',
    'totp_failed' => 'There was an error while attempting to validate TOTP.',
    '2fa_must_be_enabled' => 'The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.',
];
