// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export type { AdminNodeResource, AdminServerResource, AdminEggResource, AdminUserResource, ClientGetStartupConfigurationResponse, ClientFileObjectResource, ClientGetServerResponse, ClientGetServerResourcesResponse, ClientGetServerLogsResponse, ClientListFilesResponse, ClientListServerBackupsResponse, ClientGetExtensionJobProgressResponse, ClientSendPowerActionRequest, } from "./generated/types.gen.js";
import type { ClientGetExtensionJobProgressResponse } from "./generated/types.gen.js";
export type ExtensionJobProgress = ClientGetExtensionJobProgressResponse['data'];
