// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { AxiosInstance } from 'axios';
declare const http: AxiosInstance;
export default http;
export declare function httpErrorToHuman(cause: unknown): string;
