// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export interface NavigationBlockerLocation {
    readonly pathname: string;
    readonly params: Readonly<Record<string, string>>;
    readonly search: unknown;
}
export interface NavigationTransition {
    readonly action: 'PUSH' | 'REPLACE' | 'BACK' | 'FORWARD' | 'GO';
    readonly current: NavigationBlockerLocation;
    readonly next: NavigationBlockerLocation;
}
export interface NavigationBlockerOptions {
    /** Text of the default confirmation. Browsers show their own text when the tab closes. */
    message?: string;
    /** Also ask before the tab closes or reloads. Defaults to true. */
    beforeUnload?: boolean;
    /** Decide instead of the default confirmation; resolve true to leave the page. */
    confirm?: (transition: NavigationTransition) => boolean | Promise<boolean>;
}
export declare const UNSAVED_CHANGES_MESSAGE = "You have unsaved changes. Leave this page and discard them?";
/** Asks before leaving while `shouldBlock` holds, including back/forward and tab close. */
export declare function useNavigationBlocker(shouldBlock: boolean | (() => boolean), options?: NavigationBlockerOptions): void;
