// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export declare const hasPermission: (userPermissions: readonly string[], permission: string) => boolean;
export declare const usePermissions: (action: string | string[]) => boolean[];
