import { useState } from 'react';
import { Link, Navigate, useLocation, useSearch } from '@tanstack/react-router';
import LoginFormContainer from '@/components/auth/LoginFormContainer';
import { useAppForm } from '@/components/form';
import { useLoginCheckpoint } from '@/api/auth/queries';

export default function LoginCheckpointContainer() {
    const location = useLocation();

    // The login screen hands off the 2FA confirmation token via history state.
    const state = location.state as { token?: string } | null;
    const { redirect } = useSearch({ from: '/auth/login/checkpoint' });
    const loginCheckpoint = useLoginCheckpoint();
    const [isMissingDevice, setIsMissingDevice] = useState(false);

    const form = useAppForm({
        defaultValues: { code: '', recoveryCode: '' },
        onSubmit: async ({ value }) => {
            try {
                const response = await loginCheckpoint.mutateAsync({
                    body: {
                        confirmation_token: state?.token || '',
                        authentication_code: value.code,
                        recovery_token: value.recoveryCode || undefined,
                    },
                });

                if (response.data.complete) {
                    window.location.assign(redirect || response.data.intended || '/');
                }
            } catch {
                // Error toast is handled by the mutation.
            }
        },
    });

    if (!state?.token) {
        return <Navigate to='/auth/login' search={{ redirect }} replace />;
    }

    return (
        <LoginFormContainer form={form} title='Device Checkpoint' className='w-full flex'>
            <div className='mt-6'>
                <form.AppField name={isMissingDevice ? 'recoveryCode' : 'code'}>
                    {(field) => (
                        <field.TextField
                            light
                            title={isMissingDevice ? 'Recovery Code' : 'Authentication Code'}
                            description={
                                isMissingDevice
                                    ? 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.'
                                    : 'Enter the two-factor token generated by your device.'
                            }
                            type='text'
                            autoComplete='one-time-code'
                            autoFocus
                        />
                    )}
                </form.AppField>
            </div>
            <div className='mt-6'>
                <form.AppForm>
                    <form.SubmitButton size='xlarge'>Continue</form.SubmitButton>
                </form.AppForm>
            </div>
            <div className='mt-6 text-center'>
                <button
                    type='button'
                    onClick={() => {
                        form.setFieldValue('code', '');
                        form.setFieldValue('recoveryCode', '');
                        setIsMissingDevice((s) => !s);
                    }}
                    className='cursor-pointer appearance-none border-0 bg-transparent p-0 text-xs text-muted-foreground tracking-wide uppercase no-underline hover:text-foreground'
                >
                    {isMissingDevice ? 'I Have My Device' : "I've Lost My Device"}
                </button>
            </div>
            <div className='mt-6 text-center'>
                <Link
                    to='/auth/login'
                    search={{ redirect }}
                    className='text-xs text-muted-foreground tracking-wide uppercase no-underline hover:text-foreground'
                >
                    Return to Login
                </Link>
            </div>
        </LoginFormContainer>
    );
}
