name: 🚀 Feature Request
description: Suggest an idea for this project
body:
- type: textarea
  id: feat-to-problem
  attributes:
    label: Is your feature request related to a problem?
    description: "A clear and concise description of what the problem is."
    render: bash
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: Describe the solution you'd like
    description: "A clear and concise description of what you want to happen."
    render: bash
  validations:
    required: true

- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you've considered
    description: "A clear and concise description of any alternative solutions or features you've considered."
    render: bash
  validations:
    required: true

- type: textarea
  id: context
  attributes:
    label: Additional context
    description: "Add any other context or screenshots about the feature request here."
    render: bash
  validations:
    required: false
