// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { QueryFilters } from '@tanstack/react-query';
export type ServerDataDomain = 'server' | 'files' | 'fileContent' | 'startup' | 'backups' | 'resources';
export declare function serverDomainQueryFilters(id: string, domain: ServerDataDomain): QueryFilters;
