// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ExtensionFieldValues } from "../../../extensions/formFields.js";
export interface MountValues {
    name: string;
    description: string;
    source: string;
    target: string;
    readOnly: boolean;
    userMountable: boolean;
    extensions: ExtensionFieldValues<'admin.mount'>;
}
