// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import { Input as BaseInput } from '@base-ui/react/input';
import { NumberField } from '@base-ui/react/number-field';
interface ThemeProps {
    $isLight?: boolean;
    $hasError?: boolean;
}
type WithStringClassName<TProps> = Omit<TProps, 'className'> & {
    className?: string;
};
type TextInputProps = ThemeProps & WithStringClassName<React.ComponentProps<typeof BaseInput>>;
type NumberInputProps = ThemeProps & Pick<React.ComponentProps<typeof NumberField.Root>, 'value' | 'onValueChange' | 'min' | 'max' | 'step' | 'format' | 'disabled'> & WithStringClassName<Omit<React.ComponentProps<typeof NumberField.Input>, 'value' | 'onChange' | 'disabled'>>;
export declare const TextInput: ({ $isLight, $hasError, className, ...props }: TextInputProps) => React.JSX.Element;
export declare const FileInput: ({ className, ...props }: Omit<React.ComponentProps<"input">, "type">) => React.JSX.Element;
export declare const TextArea: ({ $isLight, $hasError, className, ...props }: ThemeProps & React.ComponentProps<"textarea">) => React.JSX.Element;
export declare const NumberInput: ({ $isLight, $hasError, className, value, onValueChange, min, max, step, format, disabled, ...props }: NumberInputProps) => React.JSX.Element;
export {};
