// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import { type SelectOption } from "../ui/Select.js";
import { type SwitchProps } from "../ui/Switch.js";
type BaseProps = {
    label?: string;
    description?: string;
    light?: boolean;
};
export type TextFieldProps = BaseProps & Omit<React.InputHTMLAttributes<HTMLInputElement>, 'name' | 'value' | 'onChange' | 'defaultValue'>;
export declare function TextField({ id, label, description, light, onBlur, 'aria-describedby': ariaDescribedBy, 'aria-invalid': ariaInvalid, ...props }: TextFieldProps): React.JSX.Element;
export type TextAreaFieldProps = BaseProps & Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>, 'name' | 'value' | 'onChange' | 'defaultValue'>;
export declare function TextAreaField({ id, label, description, light, onBlur, 'aria-describedby': ariaDescribedBy, 'aria-invalid': ariaInvalid, ...props }: TextAreaFieldProps): React.JSX.Element;
export type NumberFieldProps = BaseProps & {
    id?: string;
    min?: number;
    max?: number;
    placeholder?: string;
    disabled?: boolean;
    format?: Intl.NumberFormatOptions;
};
/** Binds a `number | null` field; an emptied input stores null. */
export declare function NumberField({ id, label, description, light, min, max, format, ...props }: NumberFieldProps): React.JSX.Element;
export type { SelectOption };
export type SelectFieldProps = BaseProps & {
    id?: string;
    options: SelectOption[];
    disabled?: boolean;
    placeholder?: string;
    emptyMessage?: string;
    onChange?: (value: string | number) => void;
    onSearchChange?: (value: string) => void;
};
export declare function SelectField({ id, label, description, light, options, disabled, placeholder, emptyMessage, onChange, onSearchChange, }: SelectFieldProps): React.JSX.Element;
export type MultiSelectFieldProps = BaseProps & {
    id?: string;
    options: SelectOption[];
    disabled?: boolean;
    placeholder?: string;
    searchPlaceholder?: string;
};
export declare function MultiSelectField({ id, label, description, light, options, disabled, placeholder, searchPlaceholder, }: MultiSelectFieldProps): React.JSX.Element;
export type SwitchFieldProps = {
    label?: string;
    description?: string;
    disabled?: boolean;
    controlPosition?: SwitchProps['controlPosition'];
    className?: string;
};
export declare function SwitchField({ label, description, disabled, controlPosition, className }: SwitchFieldProps): React.JSX.Element;
export type CheckboxFieldProps = {
    value: string;
    disabled?: boolean;
    className?: string;
};
/** Adds or removes `value` in a `string[]` field. */
export declare function CheckboxField({ value, disabled, className }: CheckboxFieldProps): React.JSX.Element;
