// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
interface Props extends Omit<React.FormHTMLAttributes<HTMLFormElement>, 'onSubmit'> {
    form: {
        handleSubmit: () => unknown;
    };
    children: React.ReactNode;
}
export default function Form({ form, children, ...props }: Props): React.JSX.Element;
export {};
