// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import { type AppFieldExtendedReactFormApi } from '@tanstack/react-form';
import type { FormAsyncValidateOrFn, FormValidateOrFn } from '@tanstack/form-core';
import { TextField, TextAreaField, NumberField, SelectField, MultiSelectField, SwitchField, CheckboxField } from "./fields.js";
import { SubmitButton } from "./SubmitButton.js";
declare const fieldComponents: {
    TextField: typeof TextField;
    TextAreaField: typeof TextAreaField;
    NumberField: typeof NumberField;
    SelectField: typeof SelectField;
    MultiSelectField: typeof MultiSelectField;
    SwitchField: typeof SwitchField;
    CheckboxField: typeof CheckboxField;
};
declare const formComponents: {
    SubmitButton: typeof SubmitButton;
};
export declare const useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: import("@tanstack/form-core").FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedReactFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, {
    TextField: typeof TextField;
    TextAreaField: typeof TextAreaField;
    NumberField: typeof NumberField;
    SelectField: typeof SelectField;
    MultiSelectField: typeof MultiSelectField;
    SwitchField: typeof SwitchField;
    CheckboxField: typeof CheckboxField;
}, {
    SubmitButton: typeof SubmitButton;
}>;
export { default as Form } from "./Form.js";
export { useFormContext, useFieldContext } from "./context.js";
export type { SelectOption } from "./fields.js";
type SyncValidator<TFormData> = FormValidateOrFn<TFormData> | undefined;
type AsyncValidator<TFormData> = FormAsyncValidateOrFn<TFormData> | undefined;
/** Types a `form` prop for a sub-component that renders `<form.AppField>` of its parent's form. */
export type AppForm<TFormData> = AppFieldExtendedReactFormApi<TFormData, SyncValidator<TFormData>, SyncValidator<TFormData>, AsyncValidator<TFormData>, SyncValidator<TFormData>, AsyncValidator<TFormData>, SyncValidator<TFormData>, AsyncValidator<TFormData>, SyncValidator<TFormData>, AsyncValidator<TFormData>, AsyncValidator<TFormData>, unknown, typeof fieldComponents, typeof formComponents>;
