// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import Button from "../elements/Button.js";
type Props = Omit<React.ComponentProps<typeof Button>, 'type'>;
/** Disabled while the form cannot submit; shows a spinner while it submits. */
export declare function SubmitButton({ children, disabled, ...props }: Props): React.JSX.Element;
export {};
