// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import { Link } from '@tanstack/react-router';
interface Props {
    isLoading?: boolean;
    size?: 'xsmall' | 'small' | 'large' | 'xlarge';
    color?: 'green' | 'red' | 'orange' | 'primary' | 'grey';
    isSecondary?: boolean;
}
declare const buttonClassName: ({ color, size, isSecondary, className, }: Omit<Props, "isLoading"> & {
    className?: string;
}) => string;
type StyleableProps = Omit<Props, 'isLoading'>;
type ButtonStyleProps<E extends React.ElementType = 'button'> = {
    as?: E;
    ref?: React.ComponentPropsWithRef<E>['ref'];
} & StyleableProps & Omit<React.ComponentPropsWithoutRef<E>, keyof StyleableProps | 'as'>;
declare const ButtonStyle: <E extends React.ElementType = "button">({ as, color, size, isSecondary, className, ref, ...props }: ButtonStyleProps<E>) => React.JSX.Element;
type ComponentProps = Omit<React.ComponentPropsWithRef<'button'>, keyof Props> & Props;
/** Defaults to `type="button"`; `isLoading` shows a spinner and disables the button. */
declare const Button: {
    ({ children, isLoading, disabled, type, ref, ...props }: ComponentProps): React.JSX.Element;
    displayName: string;
};
declare const TextButton: {
    ({ ref, ...props }: ComponentProps): React.JSX.Element;
    displayName: string;
};
declare const DangerButton: {
    ({ ref, ...props }: ComponentProps): React.JSX.Element;
    displayName: string;
};
declare const ButtonWithVariants: typeof Button & {
    Text: typeof TextButton;
    Danger: typeof DangerButton;
};
type LinkProps = Omit<React.JSX.IntrinsicElements['a'], 'ref' | keyof Props> & Props;
declare const LinkButton: (props: LinkProps) => React.JSX.Element;
declare const RouterLinkButton: (props: ButtonStyleProps<typeof Link>) => React.JSX.Element;
export { LinkButton, RouterLinkButton, ButtonStyle, buttonClassName };
export default ButtonWithVariants;
