// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
interface Props {
    action: string | string[];
    matchAny?: boolean;
    renderOnError?: React.ReactNode | null;
    children: React.ReactNode;
}
export default function Can({ action, matchAny, renderOnError, children }: Props): React.ReactNode;
export {};
