// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
type Props = Readonly<React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement> & {
    title?: string;
    borderColor?: string;
    showLoadingOverlay?: boolean;
}>;
declare const ContentBox: ({ title, borderColor, showLoadingOverlay, children, ...props }: Props) => React.JSX.Element;
export default ContentBox;
