// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
interface CopyOnClickProps {
    text: string | number | null | undefined;
    showInNotification?: boolean;
    children: React.ReactNode;
}
/** Copies `text` when its single child is clicked; a non-interactive child becomes a focusable button. */
declare const CopyOnClick: ({ text, showInNotification, children }: CopyOnClickProps) => React.JSX.Element;
export default CopyOnClick;
