// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { LucideIcon, LucideProps } from 'lucide-react';
interface Props extends Omit<LucideProps, 'ref'> {
    icon: LucideIcon;
    className?: string;
}
/** Renders a lucide icon inline at the surrounding text size (1em). */
declare const Icon: ({ icon: IconComponent, className, size, ...rest }: Props) => import("react").JSX.Element;
export default Icon;
