// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
type Props<E extends React.ElementType = 'label'> = {
    as?: E;
    isLight?: boolean;
} & Omit<React.ComponentPropsWithoutRef<E>, 'as' | 'isLight'>;
declare const Label: <E extends React.ElementType = "label">({ as, isLight, className, ...props }: Props<E>) => React.JSX.Element;
export default Label;
