// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import { type LucideIcon, type LucideProps } from 'lucide-react';
/** Every icon name this panel can render. */
export declare function loadIconNames(): Promise<readonly string[]>;
/** The icon for a name: `undefined` while the icon set loads, `null` when the name is unknown. */
export declare function useNamedIcon(name: string): LucideIcon | null | undefined;
export interface NamedIconProps extends Omit<LucideProps, 'ref' | 'name'> {
    /** A lucide icon name in kebab-case, such as `life-buoy`. */
    name: string;
    /** Rendered when the name is not a lucide icon this panel ships. */
    fallback?: LucideIcon;
}
export default function NamedIcon({ name, fallback, className, size, ...rest }: NamedIconProps): import("react").JSX.Element;
