// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
export interface PageContentBlockProps {
    title?: string;
    className?: string;
    children?: React.ReactNode;
}
declare const PageContentBlock: ({ title, className, children }: PageContentBlockProps) => React.JSX.Element;
export default PageContentBlock;
