// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
interface RenderFuncProps<T> {
    items: T[];
    isLastPage: boolean;
    isFirstPage: boolean;
}
interface Props<T> {
    data: GeneratedPaginatedResult<T>;
    showGoToLast?: boolean;
    showGoToFirst?: boolean;
    onPageSelect: (page: number) => void;
    children: (props: RenderFuncProps<T>) => React.ReactNode;
}
interface GeneratedPaginatedResult<T> {
    data: T[];
    meta: {
        pagination: {
            total: number;
            count: number;
            per_page: number;
            current_page: number;
            total_pages: number;
        };
    };
}
declare function Pagination<T>({ data, onPageSelect, children }: Props<T>): React.JSX.Element;
export default Pagination;
