// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
interface BaseProps {
    title: string;
    image: string;
    message: string;
    onRetry?: () => void;
    onBack?: () => void;
}
interface PropsWithRetry extends BaseProps {
    onRetry?: () => void;
    onBack?: never;
}
interface PropsWithBack extends BaseProps {
    onBack?: () => void;
    onRetry?: never;
}
export type ScreenBlockProps = PropsWithBack | PropsWithRetry;
declare const ScreenBlock: ({ title, image, message, onBack, onRetry }: ScreenBlockProps) => React.JSX.Element;
type ServerErrorProps = (Omit<PropsWithBack, 'image' | 'title'> | Omit<PropsWithRetry, 'image' | 'title'>) & {
    title?: string;
};
declare const ServerError: ({ title, message, onBack, onRetry }: ServerErrorProps) => React.JSX.Element;
declare const AccessDenied: ({ message }: Pick<BaseProps, "message">) => React.JSX.Element;
declare const NotFound: ({ title, message, onBack }: Partial<Pick<ScreenBlockProps, "title" | "message" | "onBack">>) => React.JSX.Element;
export { AccessDenied, ServerError, NotFound };
export default ScreenBlock;
