// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { PageContentBlockProps } from "./PageContentBlock.js";
interface Props extends PageContentBlockProps {
    /** Shown after the server name in the document title; omit to leave the title alone. */
    title?: string;
}
declare const ServerContentBlock: ({ title, children, ...props }: Props) => import("react").JSX.Element;
export default ServerContentBlock;
