// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
export type SpinnerSize = 'small' | 'base' | 'large';
interface Props {
    size?: SpinnerSize;
    centered?: boolean;
    isBlue?: boolean;
    children?: React.ReactNode;
}
type SpinnerComponentType = ((props: Props) => React.JSX.Element) & {
    displayName?: string;
    Size: Record<'SMALL' | 'BASE' | 'LARGE', SpinnerSize>;
    Suspense: ((props: Props) => React.JSX.Element) & {
        displayName?: string;
    };
};
declare const Spinner: SpinnerComponentType;
export default Spinner;
