// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type React from 'react';
import type { LucideIcon } from 'lucide-react';
interface Props {
    icon?: LucideIcon;
    title: string | React.ReactNode;
    className?: string;
    contentClassName?: string;
    children: React.ReactNode;
}
declare const TitledGreyBox: ({ icon, title, children, className, contentClassName }: Props) => React.JSX.Element;
export default TitledGreyBox;
