server {
    listen 127.0.0.1:8080;
    server_name localhost;
    access_log off;

    location = /ping {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /ping;
        fastcgi_pass 127.0.0.1:9000;
    }

    location / {
        return 404;
    }
}
