<?php

declare(strict_types=1);

namespace Pterodactyl\Console\Commands\Extensions;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Pterodactyl\Services\Extensions\ExtensionManifestValidator;
use Pterodactyl\Services\Extensions\ExtensionPermissionRegistry;
use Pterodactyl\Services\Extensions\ExtensionSettingsDefinition;
use Pterodactyl\Services\Extensions\ExtensionSettingsRegistry;

#[Description('Generate literal screen ids and frontend configuration types for an extension.')]
#[Signature('p:extension:types {path : Unpacked package path.} {--output= : Generated TypeScript file; defaults to src/client/extension-types.ts.}')]
class TypesCommand extends Command
{
    public function handle(ExtensionManifestValidator $validator, ExtensionSettingsRegistry $settings, ExtensionPermissionRegistry $permissions): int
    {
        $manifest = $validator->fromDirectory($this->argument('path'));
        $definition = $settings->get($manifest->id);
        $names = array_map(fn (array $screen): string => json_encode($screen['id'], JSON_THROW_ON_ERROR), $manifest->screens);
        $properties = [];
        foreach ($definition?->frontendConfigTypes() ?? [] as $name => $type) {
            $typescript = match ($type) {
                'array' => 'readonly ExtensionConfigValue[]',
                'object' => 'Readonly<Record<string, ExtensionConfigValue>>',
                'json' => 'ExtensionConfigValue',
                default => $type,
            };
            $properties[] = '    readonly '.json_encode($name, JSON_THROW_ON_ERROR).': '.$typescript.';';
        }

        $source = "// Generated by p:extension:types. Do not edit.\nimport type { ExtensionConfig as SdkExtensionConfig, ExtensionConfigValue } from '@pterodactyl/sdk';\n\n";
        $source .= 'export type ExtensionId = '.json_encode($manifest->id, JSON_THROW_ON_ERROR).";\n";
        $source .= 'export type ExtensionScreenId = '.($names === [] ? 'never' : implode(' | ', $names)).";\n";
        $permissionNames = array_map(fn (string $key): string => json_encode('ext.'.$manifest->id.'.'.$key, JSON_THROW_ON_ERROR), array_keys($permissions->all()[ExtensionPermissionRegistry::group($manifest->id)]['keys'] ?? []));
        $source .= 'export type ExtensionPermission = '.($permissionNames === [] ? 'never' : implode(' | ', $permissionNames)).";\n";
        $source .= "export interface ExtensionConfig extends SdkExtensionConfig {\n".implode("\n", $properties)."\n}\n";
        $publicNames = array_map(fn (string $name): string => json_encode($name, JSON_THROW_ON_ERROR), $definition?->publicConfigKeys() ?? []);
        $source .= "// Visitors who are not signed in receive only these keys; every other key is absent for them.\n";
        $source .= 'export type ExtensionPublicConfigKey = '.($publicNames === [] ? 'never' : implode(' | ', $publicNames)).";\n";
        $source .= "export type ExtensionPublicConfig = Pick<ExtensionConfig, ExtensionPublicConfigKey>;\n";
        $output = $this->option('output') ?: $manifest->path('src', 'client', 'extension-types.ts');
        File::ensureDirectoryExists(dirname($output));
        File::replace($output, $source);
        if (! $definition instanceof ExtensionSettingsDefinition) {
            $this->components->warn('No settings definition is loaded; enable the extension to include declared frontend configuration keys.');
        }

        $this->components->info("Generated extension types: {$output}");

        return self::SUCCESS;
    }
}
