// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { Options as GeneratedOptions } from "../api/generated/client/index.js";
export { client } from "../api/generated/client.gen.js";
export { createClient, createConfig } from "../api/generated/client/index.js";
export type { Client, ClientMeta, ClientOptions, Config, Options, RequestOptions, RequestResult, } from "../api/generated/client/index.js";
/** The request data every generated operation's options extend. */
export type RequestData = GeneratedOptions extends GeneratedOptions<infer TData> ? TData : never;
export { createClientConfig } from "../api/hey-api-runtime.js";
export { default as http, httpErrorToHuman } from "../api/http.js";
export { queryClient } from "../api/queryClient.js";
