// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ComponentName, ComponentReplacement } from "../extensions/componentTypes.js";
import type { ComponentType } from 'react';
import type { ExtensionTableName, ExtensionTableColumn } from "../extensions/tableTypes.js";
import { SLOT_NAMES, type SlotComponentProps, type SlotData, type ScreenImporter, type ScreenComponentProps, type ScreenOptions, type ExtensionScreenDefinition, type RouteSlotData, type SlotName, type SubuserPermissionsSlotData } from "../extensions/registry.js";
import type { UserData as SdkUser } from "../api/account/types.js";
import type { SiteSettings as SdkSiteSettings } from "../api/settings/types.js";
import type { Server as SdkServer } from "../api/server/types.js";
import { SocketEvent } from "../components/server/events.js";
export { default as Button } from "../components/elements/Button.js";
export { default as Spinner } from "../components/elements/Spinner.js";
export { default as Icon } from "../components/elements/Icon.js";
export { default as NamedIcon, loadIconNames, type NamedIconProps } from "../components/elements/NamedIcon.js";
export { default as Can } from "../components/elements/Can.js";
export { default as ContentBox } from "../components/elements/ContentBox.js";
export { default as PageContentBlock } from "../components/elements/PageContentBlock.js";
export { default as ServerContentBlock } from "../components/elements/ServerContentBlock.js";
export { default as TitledGreyBox } from "../components/elements/TitledGreyBox.js";
export { default as CopyOnClick } from "../components/elements/CopyOnClick.js";
export { default as ScreenBlock, ServerError, NotFound } from "../components/elements/ScreenBlock.js";
export { default as Label } from "../components/elements/Label.js";
export { TextInput as Input, TextArea, NumberInput } from "../components/form/controls.js";
export { Form, useAppForm, useFieldContext, useFormContext, type AppForm, type SelectOption } from "../components/form/index.js";
export { default as Select, type SelectGroup, type SelectProps, type SelectValue } from "../components/ui/Select.js";
export { default as Checkbox, type CheckboxProps } from "../components/ui/Checkbox.js";
export { default as Switch, type SwitchProps } from "../components/ui/Switch.js";
export { Alert } from "../components/elements/alert/index.js";
export { Dialog } from "../components/elements/dialog/index.js";
export { toast } from 'sonner';
export * from "./ui.js";
export { default as http, httpErrorToHuman } from "../api/http.js";
export { queryClient } from "../api/queryClient.js";
export * from "./server.js";
export * from "./mutations.js";
export * from "./navigation.js";
export * from "./localization.js";
export * from "./progress.js";
export * from "./theme.js";
export { useCurrentResource, type ExtensionResourceContext } from "../extensions/resourceContext.js";
export type { SdkUser, SdkSiteSettings, SdkServer };
export declare function useCurrentUser(): SdkUser;
export declare function useSiteSettings(): SdkSiteSettings;
export declare function useCurrentServer<TData = SdkServer>(select?: (server: SdkServer) => TData): TData | undefined;
export declare function useCurrentServerPermissions(): string[];
export { usePermissions } from "../plugins/usePermissions.js";
export { useExtensionCallback as useExtensionAction } from "../extensions/context.js";
export { SLOT_NAMES };
export type { ExtensionScreenDefinition, RouteSlotData, ScreenComponentProps, SlotName, SubuserPermissionsSlotData };
export type { AdminUserFormSlotData, CreateFormSlotData, EditFormSlotData, ExtensionFormResources, FormSlotDataMap, FormSlotName, FileManagerSlotData, FileRowSlotData, StartupFormSlotData, ScreenParent, ScreenBadgeValue, ScreenCondition, ScreenContext, ScreenMatcher, ScreenOptions, } from "../extensions/registry.js";
export type { ExtensionTableColumn, ExtensionTableName, ExtensionTableRows } from "../extensions/tableTypes.js";
export type { ExtensionFieldValue, ExtensionFieldValues, ExtensionFormFieldMap, ExtensionFormName, } from "../extensions/formFields.js";
export type { SlotComponentProps, SlotData } from "../extensions/registry.js";
export interface ExtensionMeta {
    id: string;
    version?: string;
}
export type ExtensionConfigValue = string | number | boolean | null | readonly ExtensionConfigValue[] | {
    readonly [key: string]: ExtensionConfigValue;
};
export interface ExtensionConfig {
    readonly [key: string]: ExtensionConfigValue;
}
export interface ExtensionSetupContext {
    meta: ExtensionMeta;
    /** Per-install extension settings. */
    config: ExtensionConfig;
    components: {
        replace<TName extends ComponentName>(name: TName, replacement: ComponentReplacement<TName>): void;
    };
    slots: {
        /** Mount a component at a named anchor point; see SlotName for the catalog. */
        register<TName extends SlotName>(name: TName, component: ComponentType<SlotComponentProps<SlotData<TName>>>): void;
    };
    screens: {
        /**
         * Attaches an implementation to a screen declared in extension.json `ui.screens`.
         * `options` can add a live nav badge and the `when.runtime` visibility predicate.
         */
        register(id: string, component: ScreenImporter, options?: ScreenOptions): void;
    };
    columns: {
        register<TName extends ExtensionTableName>(name: TName, column: ExtensionTableColumn<TName>): void;
    };
}
export { COMPONENT_NAMES } from "../extensions/componentTypes.js";
export type { ComponentName, ComponentModels, ComponentParts, ComponentPartProps, DefaultComponentProps, ReplacementProps, ReplacementImporter, ComponentReplacement, ServerCardModel, ServerCardState, ServerCardMetric, FileDetailsModel, FileEditorModel, FileManagerModel, FileManagerEntry, FileManagerPermissions, FileManagerActions, } from "../extensions/componentTypes.js";
export interface ExtensionDefinition {
    setup(context: ExtensionSetupContext): void;
}
/** Identity helper giving extension entrypoints full typing: `export default definePterodactylExtension({...})`. */
export declare function definePterodactylExtension(definition: ExtensionDefinition): ExtensionDefinition;
export type ConfiguredExtensionContext<TConfig extends ExtensionConfig, TScreenId extends string> = Omit<ExtensionSetupContext, 'config' | 'screens'> & {
    config: TConfig;
    screens: {
        register(id: TScreenId, component: ScreenImporter, options?: ScreenOptions): void;
    };
};
/** Like definePterodactylExtension, with `config` decoded by `parseConfig` and typed screen ids. */
export declare function defineConfiguredExtension<TConfig extends ExtensionConfig, TScreenId extends string = string>(parseConfig: (config: ExtensionConfig) => TConfig, definition: {
    setup(context: ConfiguredExtensionContext<TConfig, TScreenId>): void;
}): ExtensionDefinition;
export { SocketEvent };
export type ServerWebsocketEvent = SocketEvent | `${SocketEvent}`;
/**
 * Subscribes to a server websocket event while mounted under /server/$id.
 * Only call from server screens, server slots, or components rendered under them.
 */
export declare function useServerWebsocketEvent(event: ServerWebsocketEvent, callback: (data: string) => void | Promise<void>): void;
export declare function useCurrentServerUuid(): string | undefined;
export declare function useCurrentServerRequired(message?: string): SdkServer;
export declare function useServerPermission(permission: string | string[], matchAny?: boolean): boolean;
export type { UserValues as AdminUserFormValues } from "../api/admin/users/types.js";
