// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export interface ExtensionTranslation {
    locale: string;
    ready: boolean;
    t(key: string, values?: Record<string, string | number>): string;
}
/** resources/lang/<locale>/<group>.php, registered with loadExtensionTranslations(). */
export declare function useExtensionTranslation(group?: string): ExtensionTranslation;
