// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { SdkBackup, SdkServerStartup } from "./server.js";
import type { ClientSendPowerActionRequest } from "../api/extensionTypes.js";
export interface SdkMutation<TInput, TOutput = void> {
    isPending: boolean;
    error: unknown;
    data: TOutput | undefined;
    mutateAsync(input: TInput): Promise<TOutput>;
    reset(): void;
}
export interface SdkFileSelection {
    directory: string;
    files: string[];
}
export type SdkPowerSignal = ClientSendPowerActionRequest['signal'];
export declare function useCreateServerDirectory(uuid: string): SdkMutation<{
    directory: string;
    name: string;
}>;
export declare function useRenameServerFiles(uuid: string): SdkMutation<{
    directory: string;
    files: {
        from: string;
        to: string;
    }[];
}>;
export declare function useDeleteServerFiles(uuid: string): SdkMutation<SdkFileSelection>;
export declare function useWriteServerFile(uuid: string): SdkMutation<{
    file: string;
    content: string;
}>;
export declare function useUpdateServerStartupVariable(uuid: string): SdkMutation<{
    key: string;
    value: string;
}, SdkServerStartup['data'][number]>;
export declare function useSetServerDockerImage(uuid: string): SdkMutation<{
    image: string;
}>;
export declare function useCreateServerBackup(uuid: string): SdkMutation<{
    name?: string;
    ignored?: string;
    isLocked: boolean;
}, SdkBackup>;
/** The API requires the control permission that matches the signal. */
export declare function useSendServerPower(uuid: string): SdkMutation<{
    signal: SdkPowerSignal;
}>;
/** The API requires control.console and a running server. */
export declare function useSendServerCommand(uuid: string): SdkMutation<{
    command: string;
}>;
