// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import { type UseQueryResult } from '@tanstack/react-query';
import type { ExtensionJobProgress } from "../api/extensionTypes.js";
import type { SdkServerQueryOptions } from "./server.js";
export type { ExtensionJobProgress } from "../api/extensionTypes.js";
/** The key includes both the extension namespace and the subject. */
export declare function extensionProgressQueryOptions(extension: string, job: string, serverUuid?: string): SdkServerQueryOptions<ExtensionJobProgress>;
/** Poll running jobs, stop terminal/expired jobs, and recover the latest snapshot on reconnect. */
export declare function useExtensionJobProgress(job: string | undefined, options?: {
    serverUuid?: string;
}): UseQueryResult<ExtensionJobProgress, unknown>;
