// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ComponentModels, ComponentName, ReplacementProps, ServerCardModel, FileDetailsModel, FileEditorModel, FileManagerEntry, FileManagerModel } from "../extensions/componentTypes.js";
import { type ComponentType, type ReactNode } from 'react';
import { type QueryClient } from '@tanstack/react-query';
import type { ExtensionResourceContext } from "../extensions/resourceContext.js";
import type { HistoryState } from '@tanstack/react-router';
import { type PanelDestination, type PanelSearch } from "./navigation.js";
import type { SdkServer, SdkSiteSettings, SdkUser } from "./index.js";
import type { ServerWebsocketEvent } from "./index.js";
export interface ExtensionTestHostOptions {
    extensionId?: string;
    /** The extension's `ui.prefix`, so its prefixed classes merge with a core component's as they do in the panel. */
    prefix?: string;
    path?: string;
    user?: SdkUser;
    siteSettings?: SdkSiteSettings;
    server?: SdkServer;
    resource?: ExtensionResourceContext;
}
export interface ExtensionTestLocation {
    pathname: string;
    search: PanelSearch;
    state: HistoryState;
}
export interface ExtensionTestHost {
    Wrapper: ComponentType<{
        children?: ReactNode;
    }>;
    queryClient: QueryClient;
    navigate(destination: PanelDestination): Promise<void>;
    location(): ExtensionTestLocation;
    emitWebsocket(event: ServerWebsocketEvent, data: string): void;
    setConnected(connected: boolean): void;
    dispose(): void;
}
export declare function createTestServer(options?: {
    identifier?: string;
    uuid?: string;
    name?: string;
    owner?: boolean;
    permissions?: string[];
    status?: SdkServer['attributes']['status'];
    eggFeatures?: string[];
    eggTags?: string[];
}): SdkServer;
/** Create one host per test; call dispose after unmounting its Wrapper. */
export declare function createExtensionTestHost(options?: ExtensionTestHostOptions): ExtensionTestHost;
export declare function createTestServerCard(options?: Partial<ServerCardModel>): ServerCardModel;
export declare function createTestFileDetails(options?: Partial<FileDetailsModel>): FileDetailsModel;
export declare function createTestFileEditor(options?: Partial<FileEditorModel>): FileEditorModel;
export declare function createTestFileManagerEntry(options?: Partial<FileManagerEntry>): FileManagerEntry;
export declare function createTestFileManager(options?: Partial<FileManagerModel>): FileManagerModel;
export interface ComponentTestHost<TName extends ComponentName> {
    Wrapper: ComponentType<{
        children?: ReactNode;
    }>;
    props: ReplacementProps<TName>;
    /** Call after unmounting the Wrapper. */
    dispose(): void;
}
/** Test presentation against the native default and parts without issuing core queries. */
export declare function createComponentTestHost<TName extends ComponentName>(name: TName, options: {
    model: ComponentModels[TName];
    extensionId?: string;
    prefix?: string;
}): ComponentTestHost<TName>;
