// Generated by scripts/generate-sdk-types.mjs. Do not edit.
/**
 * Calls `listener`, at most once a frame, after a stylesheet or an `<html>` attribute changes.
 * It is a hint, not a diff: compare the values you read. Returns the unsubscribe function.
 */
export declare function onThemeChange(listener: () => void): () => void;
/** Report a token change the DOM cannot reveal (CSSOM rule edits, adopted stylesheets). */
export declare function notifyThemeChange(): void;
/** The current value of a token on `<html>`, e.g. `readThemeToken('--chart-1')`; '' when unset. */
export declare function readThemeToken(name: `--${string}`): string;
