// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import { type DOMAttributes, type ReactElement, type ReactNode, type RefAttributes } from 'react';
export { default as DropdownMenu, DropdownMenuItem, ContextDropdownMenu, } from "../components/elements/dropdown/DropdownMenu.js";
export { default as Pagination } from "../components/elements/Pagination.js";
export { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "../components/ui/empty.js";
export interface TableColumn<TRow> {
    id: string;
    label: ReactNode;
    cell(row: TRow): ReactNode;
}
export interface TableProps<TRow> {
    rows: readonly TRow[];
    columns: readonly TableColumn<TRow>[];
    keyOf(row: TRow): string;
    /** Replaces the table when there are no rows, typically an `Empty`; a string renders as its description. */
    emptyState: ReactNode;
    isFetching?: boolean;
    className?: string;
}
export declare function Table<TRow>({ rows, columns, keyOf, ...props }: TableProps<TRow>): ReactElement;
export interface TooltipProps {
    content: ReactNode;
    children: ReactElement<DOMAttributes<Element> & RefAttributes<Element> & {
        className?: string;
    }>;
    disabled?: boolean;
    className?: string;
    placement?: 'top' | 'bottom' | 'left' | 'right';
}
export declare function Tooltip(props: TooltipProps): ReactElement;
