// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { ExtensionFieldValues } from "../../../extensions/formFields.js";
export interface LocationValues {
    short: string;
    long: string;
    extensions: ExtensionFieldValues<'admin.location'>;
}
