// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import ConfirmationDialog from "./ConfirmationDialog.js";
type ConfirmationDialogProps = React.ComponentProps<typeof ConfirmationDialog>;
type TriggerProps = {
    onClick: () => void;
};
type ConfirmationDialogTriggerProps = Omit<ConfirmationDialogProps, 'open' | 'onClose' | 'onConfirmed'> & {
    /** A returned promise keeps the dialog pending until it settles; rejections are swallowed. */
    onConfirmed: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>, close: () => void) => void | Promise<void>;
    trigger: (props: TriggerProps) => React.ReactNode;
};
export default function ConfirmationDialogTrigger({ onConfirmed, trigger, pending, ...props }: ConfirmationDialogTriggerProps): React.JSX.Element;
export {};
