// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import type { RenderDialogProps } from "./types.js";
type ConfirmationProps = Omit<RenderDialogProps, 'children'> & {
    children?: React.ReactNode;
    confirm?: string | undefined;
    /** Disables both actions, shows a spinner on the confirm button and ignores close requests. */
    pending?: boolean;
    onConfirmed: (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void;
};
export default function ConfirmationDialog({ confirm, pending, children, onConfirmed, preventExternalClose, hideCloseIcon, ...props }: ConfirmationProps): React.JSX.Element;
export {};
