// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import type { DialogContextType } from "./types.js";
export declare const DialogContext: React.Context<DialogContextType>;
