// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
type TriggerProps = {
    onClick: () => void;
};
type DialogStateProps = {
    open: boolean;
    onClose: () => void;
};
type DialogTriggerProps = {
    children: (props: DialogStateProps) => React.ReactNode;
    trigger: (props: TriggerProps) => React.ReactNode;
};
export default function DialogTrigger({ children, trigger }: DialogTriggerProps): React.JSX.Element;
export {};
