// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import type { RenderDialogProps } from "./types.js";
export default function DialogComponent({ open, title, description, onClose, hideCloseIcon, preventExternalClose, children, }: RenderDialogProps): React.JSX.Element;
