// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import DialogComponent from "./Dialog.js";
import DialogTrigger from "./DialogTrigger.js";
import ConfirmationDialog from "./ConfirmationDialog.js";
import ConfirmationDialogTrigger from "./ConfirmationDialogTrigger.js";
export { useDialogState } from "./useDialogState.js";
declare const Dialog: typeof DialogComponent & {
    Confirm: typeof ConfirmationDialog;
    ConfirmTrigger: typeof ConfirmationDialogTrigger;
    Footer: ({ children }: {
        children: React.ReactNode;
    }) => import("react").JSX.Element;
    Icon: ({ type, position, className }: import("./types.js").DialogIconProps) => null;
    Trigger: typeof DialogTrigger;
};
export { Dialog };
export * from "./types.js";
export * from "./context.js";
