// Generated by scripts/generate-sdk-types.mjs. Do not edit.
export declare const useDialogState: (initialOpen?: boolean) => {
    open: boolean;
    setOpen: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    show: () => void;
    hide: () => void;
    toggle: () => void;
};
