// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import React from 'react';
import { Menu } from '@base-ui/react/menu';
import type { LucideIcon } from 'lucide-react';
interface DropdownMenuProps {
    /** Rendered inside the trigger `<button>`. */
    triggerContent: React.ReactNode;
    triggerClassName?: string;
    openOnHover?: boolean;
    children: React.ReactNode;
    className?: string;
}
declare function DropdownMenu({ triggerContent, triggerClassName, openOnHover, children, className }: DropdownMenuProps): React.JSX.Element;
interface ContextDropdownMenuProps {
    className?: string;
    menuClassName?: string;
    children: React.ReactNode;
    items: React.ReactNode;
}
/** Opens `items` at the cursor on right-click or long-press over `children`. */
export declare function ContextDropdownMenu({ className, menuClassName, children, items }: ContextDropdownMenuProps): React.JSX.Element;
interface ItemProps extends React.ComponentProps<typeof Menu.Item> {
    icon?: LucideIcon;
    danger?: boolean;
    description?: React.ReactNode;
}
/** An item for either DropdownMenu or ContextDropdownMenu. */
export declare function DropdownMenuItem({ icon, danger, description, className, children, ...props }: ItemProps): React.JSX.Element;
declare const DropdownMenuWithItems: typeof DropdownMenu & {
    Item: typeof DropdownMenuItem;
};
export default DropdownMenuWithItems;
