// Generated by scripts/generate-sdk-types.mjs. Do not edit.
import type { NumberInputValue } from "../numberInput.js";
import type { ExtensionFieldValues } from "../../../extensions/formFields.js";
export interface DatabaseHostFormValues {
    name: string;
    host: string;
    port: NumberInputValue;
    username: string;
    password: string;
    nodeId: string;
    extensions: ExtensionFieldValues<'admin.databaseHost'>;
}
